// This file is auto-generated by generate-article-index.js. Do not edit manually.

import articleData_2025_10_12_संवादकीय_दिवाळी_२०२५ from "./articles/2025_10_12_संवादकीय-दिवाळी-२०२५.js";
import articleData_2025_10_12_मालकी from "./articles/2025_10_12_मालकी.js";
import articleData_2025_10_12_पैसे_आणि_बरंच_काही from "./articles/2025_10_12_पैसे-आणि-बरंच-काही.js";
import articleData_2025_10_12_अर्थपूर्ण_भासे_मज_हा from "./articles/2025_10_12_अर्थपूर्ण-भासे-मज-हा.js";
import articleData_2025_10_12_अनुक्रमणिका_दिवाळी_२०२५ from "./articles/2025_10_12_अनुक्रमणिका-दिवाळी-२०२५.js";
import articleData_2025_10_12_27778_2 from "./articles/2025_10_12_27778-2.js";
import articleData_2025_10_03_palakneeti_diwali_anka_2025_announcement from "./articles/2025_10_03_palakneeti-diwali-anka-2025-announcement.js";
import articleData_2025_09_15_संवादकीय_11 from "./articles/2025_09_15_संवादकीय-11.js";
import articleData_2025_09_15_सप्टेंबर_२०२५ from "./articles/2025_09_15_सप्टेंबर-२०२५.js";
import articleData_2025_09_15_चित्राभोवतीचे_प्रश्न_सप from "./articles/2025_09_15_चित्राभोवतीचे-प्रश्न-सप.js";
import articleData_2025_09_15_गोष्ट_निरंतर_ध्यासाची from "./articles/2025_09_15_गोष्ट-निरंतर-ध्यासाची.js";
import articleData_2025_09_15_आनंदी_कलाकार from "./articles/2025_09_15_आनंदी-कलाकार.js";
import articleData_2025_09_15_आनंदाचे_डोही from "./articles/2025_09_15_आनंदाचे-डोही.js";
import articleData_2025_09_15_आनंदशोध from "./articles/2025_09_15_आनंदशोध.js";
import articleData_2025_09_15_आई_रडतेय from "./articles/2025_09_15_आई-रडतेय.js";
import articleData_2025_09_03_शिकता_शिकवताना from "./articles/2025_09_03_शिकता-शिकवताना.js";
import articleData_2025_08_15_वॉल्डॉर्फ_जर्नी from "./articles/2025_08_15_वॉल्डॉर्फ-जर्नी.js";
import articleData_2025_08_15_भिंत_बोलकी_झाली from "./articles/2025_08_15_भिंत-बोलकी-झाली.js";
import articleData_2025_08_15_ऑगस्ट_२०२५ from "./articles/2025_08_15_ऑगस्ट-२०२५.js";
import articleData_2025_08_15_27675_2 from "./articles/2025_08_15_27675-2.js";

const ARTICLES = [
  {
    "2025_10_12_संवादकीय-दिवाळी-२०२५":
      articleData_2025_10_12_संवादकीय_दिवाळी_२०२५,
  },
  { "2025_10_12_मालकी": articleData_2025_10_12_मालकी },
  {
    "2025_10_12_पैसे-आणि-बरंच-काही": articleData_2025_10_12_पैसे_आणि_बरंच_काही,
  },
  {
    "2025_10_12_अर्थपूर्ण-भासे-मज-हा":
      articleData_2025_10_12_अर्थपूर्ण_भासे_मज_हा,
  },
  {
    "2025_10_12_अनुक्रमणिका-दिवाळी-२०२५":
      articleData_2025_10_12_अनुक्रमणिका_दिवाळी_२०२५,
  },
  { "2025_10_12_27778-2": articleData_2025_10_12_27778_2 },
  {
    "2025_10_03_palakneeti-diwali-anka-2025-announcement":
      articleData_2025_10_03_palakneeti_diwali_anka_2025_announcement,
  },
  { "2025_09_15_संवादकीय-11": articleData_2025_09_15_संवादकीय_11 },
  { "2025_09_15_सप्टेंबर-२०२५": articleData_2025_09_15_सप्टेंबर_२०२५ },
  {
    "2025_09_15_चित्राभोवतीचे-प्रश्न-सप":
      articleData_2025_09_15_चित्राभोवतीचे_प्रश्न_सप,
  },
  {
    "2025_09_15_गोष्ट-निरंतर-ध्यासाची":
      articleData_2025_09_15_गोष्ट_निरंतर_ध्यासाची,
  },
  { "2025_09_15_आनंदी-कलाकार": articleData_2025_09_15_आनंदी_कलाकार },
  { "2025_09_15_आनंदाचे-डोही": articleData_2025_09_15_आनंदाचे_डोही },
  { "2025_09_15_आनंदशोध": articleData_2025_09_15_आनंदशोध },
  { "2025_09_15_आई-रडतेय": articleData_2025_09_15_आई_रडतेय },
  { "2025_09_03_शिकता-शिकवताना": articleData_2025_09_03_शिकता_शिकवताना },
  { "2025_08_15_वॉल्डॉर्फ-जर्नी": articleData_2025_08_15_वॉल्डॉर्फ_जर्नी },
  { "2025_08_15_भिंत-बोलकी-झाली": articleData_2025_08_15_भिंत_बोलकी_झाली },
  { "2025_08_15_ऑगस्ट-२०२५": articleData_2025_08_15_ऑगस्ट_२०२५ },
  { "2025_08_15_27675-2": articleData_2025_08_15_27675_2 },
];

export default ARTICLES;
